// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 시드: 건축HUB·카카오 실호출로 Building 생성 (ADR-0012). 실행: npm run db:seed
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma Postgres 풀러는 트랜잭션 모드이므로 migrate/Studio는 direct 연결을 쓴다.
    // 런타임 연결은 src/lib/db.ts의 DATABASE_URL(pooled)이 담당한다 (ADR-0013).
    url: process.env["DIRECT_URL"],
  },
});
